name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "--- Installing requirements.txt ---"
          pip install -v -r requirements.txt
          echo "--- Installing dev-requirements.txt ---"
          pip install -v -r dev-requirements.txt
          python -m pip install ruff
          echo "--- Downloading spacy model en_core_web_sm ---"
          python -m spacy download en_core_web_sm

      - name: Verify black installation
        run: |
          echo "--- Verifying black installation ---"
          python -m black --version

      - name: Verify installed packages
        run: |
          echo "--- PYTHON VERSION AND EXECUTABLE ---"
          python --version
          which python
          echo "--- PIP FREEZE ---"
          pip freeze
          echo "--- TRYING TO IMPORT SPACY IN PYTHON ---"
          python -c "import sys; print(f'Python sys.path: {sys.path}'); import spacy; print('Spacy imported successfully'); print(f'Spacy version: {spacy.__version__}'); print(f'Spacy path: {spacy.__path__}')"

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings --quiet

      - name: Show Black diff
        run: |
          echo "--- Showing black diff ---"
          python -m black --diff .
        continue-on-error: true # Allow this step to fail without stopping the workflow

      - name: Lint with black
        run: |
          echo "--- Ensuring black is installed ---"
          python -m pip install black
          python -m black --check .

      - name: Lint with ruff
        shell: bash
        run: |
          echo "PATH before: $PATH"
          python -m pip install --upgrade pip
          python -m pip install --user ruff
          export PATH="$HOME/.local/bin:$PATH"
          echo "PATH after: $PATH"
          python -m ruff check .

      - name: Type check with mypy
        run: |
          echo "--- Ensuring mypy is installed ---"
          python -m pip install mypy
          echo "--- Running mypy type check ---"
          python -m mypy .
