name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "--- Installing requirements.txt ---"
          pip install -v -r requirements.txt
          echo "--- Installing dev-requirements.txt ---"
          pip install -v -r dev-requirements.txt

      - name: Verify installed packages
        run: |
          echo "--- PYTHON VERSION AND EXECUTABLE ---"
          python --version
          which python
          echo "--- PIP FREEZE ---"
          pip freeze
          echo "--- TRYING TO IMPORT SPACY IN PYTHON ---"
          python -c "import sys; print(f'Python sys.path: {sys.path}'); import spacy; print('Spacy imported successfully'); print(f'Spacy version: {spacy.__version__}'); print(f'Spacy path: {spacy.__path__}')"

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings --quiet

      - name: Lint with black
        run: black --check .

      - name: Lint with ruff
        run: ruff .

      - name: Type check with mypy
        run: mypy .
